apiVersion: v1
kind: Pod
metadata:
  name: meesho-pod
spec: 
  containers:
    - name: meesho-cont
      image: docker pull swarupa1506/meesho-app-web:v1.1.0
      ports:
        - containerport: 80
        

